"""production_hardening

Revision ID: 164f64a3235a
Revises: ab319c426fe6
Create Date: 2026-06-20 11:02:09.130515

"""
from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision = '164f64a3235a'
down_revision = 'ab319c426fe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"
    
    if not is_sqlite:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('resume_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_text', app.db.models.EncryptedString(), nullable=False),
    sa.Column('embedding', app.db.models.Vector(384), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_chunks_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_chunks_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_chunks_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(length=255), nullable=True))
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('pairing_codes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_unique_constraint("uq_sessions_refresh_token_hash", ['refresh_token_hash'])

    if not is_sqlite:
        op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_self ON users FOR ALL USING (id = auth.uid());")
        
        op.execute("ALTER TABLE resumes ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_resumes ON resumes FOR ALL USING (user_id = auth.uid());")
        
        op.execute("ALTER TABLE resume_chunks ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_chunks ON resume_chunks FOR ALL USING (user_id = auth.uid());")
        
        op.execute("ALTER TABLE interview_sessions ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_sessions ON interview_sessions FOR ALL USING (user_id = auth.uid());")
        
        op.execute("ALTER TABLE session_messages ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_messages ON session_messages FOR ALL USING (session_id IN (SELECT id FROM interview_sessions WHERE user_id = auth.uid()));")
        
        op.execute("ALTER TABLE questions ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_questions ON questions FOR ALL USING (session_id IN (SELECT id FROM interview_sessions WHERE user_id = auth.uid()));")
        
        op.execute("ALTER TABLE responses ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_responses ON responses FOR ALL USING (question_id IN (SELECT q.id FROM questions q JOIN interview_sessions s ON q.session_id = s.id WHERE s.user_id = auth.uid()));")
        
        op.execute("ALTER TABLE devices ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_devices ON devices FOR ALL USING (user_id = auth.uid());")
        
        op.execute("ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;")
        op.execute("CREATE POLICY user_login_sessions ON sessions FOR ALL USING (user_id = auth.uid());")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    if not is_sqlite:
        op.execute("DROP POLICY IF EXISTS user_login_sessions ON sessions;")
        op.execute("ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_devices ON devices;")
        op.execute("ALTER TABLE devices DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_responses ON responses;")
        op.execute("ALTER TABLE responses DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_questions ON questions;")
        op.execute("ALTER TABLE questions DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_messages ON session_messages;")
        op.execute("ALTER TABLE session_messages DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_sessions ON interview_sessions;")
        op.execute("ALTER TABLE interview_sessions DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_chunks ON resume_chunks;")
        op.execute("ALTER TABLE resume_chunks DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_resumes ON resumes;")
        op.execute("ALTER TABLE resumes DISABLE ROW LEVEL SECURITY;")
        
        op.execute("DROP POLICY IF EXISTS user_self ON users;")
        op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY;")

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint("uq_sessions_refresh_token_hash", type_='unique')
        batch_op.drop_index(batch_op.f('ix_sessions_family_id'))
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('pairing_codes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.TEXT(), nullable=True))
        batch_op.drop_column('device_id')

    with op.batch_alter_table('resume_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_chunks_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_chunks_resume_id'))
        batch_op.drop_index(batch_op.f('ix_resume_chunks_content_hash'))

    op.drop_table('resume_chunks')
    # ### end Alembic commands ###

